---
- hosts: ClamAV_centos7
  vars:
    hello: Ansible

  environment:
#    https_proxy: 
#    http_proxy: 
#    no_proxy: 

  tasks:
  - name: Install EPEL
    yum:
      name:
       - epel-release 
      state: latest
      disable_gpg_check: yes 
    tags: install

#  - name: EPEL REPO SET1
#    shell: cp -r /etc/yum.repos.d /etc/yum.repos.d.bak
#    tags: configuration


  - name: EPEL REPO SET
    copy:
      src=epel-7/
      dest=/etc/
      backup=yes
      force=yes
    tags: epel_configuration

  - name: Install ClamAV
    yum:
      name:
       - clamav
       - clamd
       - clamav-update
       - clamav-data
       - clamav-devel
       - clamav-lib
       - clamav-milter
      state: latest
      disable_gpg_check: yes
    tags: install_and_update

  - name: Update ClamAV DAT
    shell: /usr/bin/freshclam --quiet --no-warnings
    tags: update_clamav_dat

  - name: ClamAV SET
    shell: sed -e 's|^#TCPAddr|TCPAddr|g' -e 's|^#TCPSocket|TCPSocket|g' -i.bak /etc/clamd.d/scan.conf
    tags: clamav_set
